[package]
name = "cggmp24-key-refresh"
version = "0.7.0-alpha.4"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "CGGMP24 key share refresh"
repository = "https://github.com/LFDT-Lockness/cggmp21"
categories = ["algorithms", "cryptography"]
keywords = ["mpc", "threshold-signatures", "tss", "key-refresh"]

[dependencies]
cggmp24-keygen = { workspace = true }
key-share = { workspace = true, features = ["serde"] }
hd-wallet = { workspace = true, optional = true }

generic-ec = { workspace = true, features = ["serde", "udigest", "hash-to-scalar"] }
generic-ec-zkp = { workspace = true, features = ["serde", "udigest"] }
udigest = { workspace = true, features = ["derive"] }

round-based = { workspace = true, features = ["derive"] }

sha2 = { workspace = true }
digest = { workspace = true }
rand_core = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true }
hex = { workspace = true, features = ["serde"] }

futures-util = { workspace = true }

displaydoc = { workspace = true }
thiserror = { workspace = true, optional = true }

[features]
default = ["std"]

std = ["thiserror", "key-share/std", "udigest/std", "cggmp24-keygen/std"]
hd-wallet = ["dep:hd-wallet", "key-share/hd-wallet", "cggmp24-keygen/hd-wallet"]
state-machine = ["round-based/state-machine"]
