[workspace]
resolver = "2"
members = [
    "cggmp24",
    "cggmp24-keygen",
    "cggmp24-key-refresh",
    "key-share",
    "paillier-zk",
    "tests",
]
exclude = [
    "wasm/no_std",
]

[workspace.dependencies]
cggmp24 = { version = "0.7.0-alpha.4", default-features = false, path = "cggmp24" }
cggmp24-keygen = { version = "0.7.0-alpha.4", path = "cggmp24-keygen" }
cggmp24-key-refresh = { version = "0.7.0-alpha.4", path = "cggmp24-key-refresh" }
key-share = { version = "0.7", path = "key-share", default-features = false }
paillier-zk = { version = "0.7.0-alpha.4", path = "paillier-zk", default-features = false }

fast-paillier = { version = "0.3.2", default-features = false }
generic-ec = { version = "0.5", default-features = false }
generic-ec-zkp = { version = "0.5", default-features = false }
round-based = { version = "0.4.1", default-features = false }

udigest = { version = "0.2.1", default-features = false }

digest = { version = "0.10", default-features = false }
sha2 = { version = "0.10", default-features = false }

rand = "0.8"
rand_core = { version = "0.6", default-features = false }
rand_hash = { version = "0.1" }
rand_dev = "0.1"

futures = { version = "0.3", default-features = false }
futures-util = { version = "0.3", default-features = false }

anyhow = "1"
thiserror = "1"
displaydoc = { version = "0.2", default-features = false }

serde = { version = "1", default-features = false }
serde_with = { version = "2", default-features = false }
serde_json = "1"
hex = { version = "0.4", default-features = false }

hd-wallet = { version = "0.7", default-features = false }

generic-tests = "0.1"

# Make the backend less slow in debug builds to speed up tests
[profile.dev.package]
num-bigint.opt-level = 3
num-traits.opt-level = 3
num-integer.opt-level = 3
glass_pumpkin.opt-level = 3
