[package]
name = "cggmp21"
version = "0.0.0"
edition = "2021"

license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic-ec = { git = "https://github.com/dfns-labs/generic-ec", branch = "d", features = ["serde"] }
generic-ec-zkp = { git = "https://github.com/dfns-labs/generic-ec", branch = "d" }
round-based = { git = "https://github.com/Zengo-X/round-based-protocol", branch = "round-based2", features = ["derive"] }
libpaillier = "0.4"

digest = "0.10"
sha2 = "0.10"
rand_core = "0.6"

futures = "0.3"

thiserror = "1"
phantom-type = "0.4"

[dev-dependencies]
generic-tests = "0.1"
generic-ec = { git = "https://github.com/dfns-labs/generic-ec", branch = "d", features = ["all-curves"] }

rand_dev = "0.1"
