[workspace]
resolver = "2"
members = [
    "cggmp21",
    "cggmp21-keygen",
    "key-share",
    "tests",
]
exclude = [
    "wasm/no_std",
]

[patch.crates-io.round-based]
git = "https://github.com/dfns/round-based"
branch = "state-machine"
