[package]
name = "cggmp21"
version = "0.0.0"
edition = "2021"

license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic-ec = { git = "https://github.com/dfns-labs/generic-ec", branch = "d", features = ["serde"] }
generic-ec-zkp = { git = "https://github.com/dfns-labs/generic-ec", branch = "d" }
round-based = { git = "https://github.com/Zengo-X/round-based-protocol", branch = "round-based2", features = ["derive"] }

libpaillier = { version = "0.5", default-features = false }
paillier-zk = { git = "https://github.com/dfns-labs/paillier-zk", branch = "temp-2022-12-20", default-features = false }

digest = "0.10"
sha2 = "0.10"
rand_core = "0.6"

futures = "0.3"

thiserror = "1"
phantom-type = "0.4"

serde = { version = "1", features = ["derive"] }
serde_with = "2"
hex = { version = "0.4", default-features = false, features = ["serde"] }

[dev-dependencies]
generic-ec = { git = "https://github.com/dfns-labs/generic-ec", branch = "d", features = ["serde", "all-curves"] }
round-based = { git = "https://github.com/Zengo-X/round-based-protocol", branch = "round-based2", features = ["derive", "dev"] }

rand = "0.8"
rand_dev = "0.1"
rand_chacha = "0.3"

tokio = { version = "1", features = ["macros"] }

generic-tests = "0.1"
test-case = "2.2"

serde_json = "1"

[features]
default = ["libpaillier/gmp"]
