[workspace]
resolver = "2"
members = [
    "cggmp21",
    "cggmp21-keygen",
    "key-share",
    "tests",
]

[patch.crates-io.generic-ec]
git = "https://github.com/dfns/generic-ec"
branch = "better-compact"
