[package]
name = "crates-compile-in-nostd-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
# Only the crates below have wasm/no_std support
key-share = { path = "../../key-share", default-features = false, features = ["serde", "hd-wallets", "spof", "udigest"] }

[patch.crates-io.generic-ec]
git = "https://github.com/dfns/generic-ec"
branch = "prefer-compact"
