on:
  push:
    tags:
      - 'v*'
      - 'key-share-v*'
      - 'cggmp24-keygen-v*'
      - 'paillier-zk-v*'
  workflow_dispatch:

name: Publish

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  publish-cggmp24:
    name: Publish cggmp24
    environment: crates.io
    runs-on: ubuntu-latest
    if: >-
      github.ref_type == 'tag'
      && startsWith(github.ref_name, 'v')
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
    - run: cargo publish -p cggmp24
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}

  publish-key-share:
    name: Publish key-share
    environment: crates.io
    runs-on: ubuntu-latest
    if: >-
      github.ref_type == 'tag'
      && startsWith(github.ref_name, 'key-share-v')
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
    - run: cargo publish -p key-share
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}

  publish-cggmp24-keygen:
    name: Publish cggmp24-keygen
    environment: crates.io
    runs-on: ubuntu-latest
    if: >-
      github.ref_type == 'tag'
      && startsWith(github.ref_name, 'cggmp24-keygen-v')
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
    - run: cargo publish -p cggmp24-keygen
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}

  publish-paillier-zk:
    name: Publish paillier-zk
    environment: crates.io
    runs-on: ubuntu-latest
    if: >-
      github.ref_type == 'tag'
      && startsWith(github.ref_name, 'paillier-zk-v')
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
    - run: cargo publish -p paillier-zk
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
