name: Check README

on:
  pull_request:
    branches: [ "*" ]

jobs:
  check_readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-hakari
      uses: baptiste0928/cargo-install@v1
      with:
        crate: cargo-readme
    - name: Check that readme matches lib.rs
      run: |
        cp README.md README-copy.md
        make readme
        diff README.md README-copy.md