name: Check README

permissions:
  contents: read

on:
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  check_readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
    - name: Install cargo-hakari
      uses: baptiste0928/cargo-install@77fc781ff2a66b362d815793ec7bd69b50d0e549 #v1
      with:
        crate: cargo-rdme
    - name: Check that readme matches lib.rs
      run: |
        cp README.md README-copy.md
        make readme
        diff README.md README-copy.md
    - name: Check that table of contents matches docs/toc-cggmp24.md
      run: |
        cp docs/toc-cggmp24.md docs/toc-cggmp24-copy.md
        make toc-cggmp24
        diff docs/toc-cggmp24.md docs/toc-cggmp24-copy.md
