name: Rust

on:
  push:
    branches: [ "m" ]
  pull_request:
    branches: [ "*" ]
  # schedule:
  #   - cron: '0 5 * * *'

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v3
      with:
        name: benchmark-tool
        path: target/release/measure_perf
    - name: Run tests
      run: cargo test -r
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy --all --lib --exclude cggmp21-tests -- --no-deps -D clippy::all -D clippy::unwrap_used -D clippy::expect_used
    - name: Run clippy tests
      run: cargo clippy --tests --lib -- -D clippy::all
  bench:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: benchmark-tool
    - name: Set file permissions
      run: chmod +x ./measure_perf
    - name: Run benchmarks
      run: |
        ./measure_perf -n 3 --no-bench-primes-gen > perf_output
        sed -e '/PERF_OUTPUT/{r perf_output' -e 'd}' .github/pr-comment.tpl > pr-comment
    - name: Leave PR comment
      continue-on-error: true
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: bench
        path: pr-comment
